# Change these first
owner: KieranHolroyd # Your GitHub username
repo: monitoring # Your Github repository name

# Add your sites here
sites:
  - name: Dough.
    url: https://doughpizza.org
  - name: Kieran.dev
    url: https://kieran.dev
  - name: Nitrexdesign.co.uk
    url: https://nitrexdesign.co.uk

status-website:
  cname: monitoring.kieran.dev
  logoUrl: https://nitrexdesign.co.uk/logo.svg
  name: Monitoring
  introTitle: "Currently Monitor All Infrastructure for Kieran Holroyd."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

notifications:
  - type: discord
